version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./Backend:/var/www
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./Frontend
    container_name: react_app
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Backend:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network: