version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: laravel_backend
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: booking_db
      DB_USERNAME: root
      DB_PASSWORD: 
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: react_frontend
    ports:
      - "80:80"

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"