server {
    listen 80;

    location / {
        root /var/www/your_project/Frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://backend:9000;
    }
}